'use client'

import { useState } from 'react'
import Image from 'next/image'
import { ArrowRight, BedDouble, Bath, Maximize, Heart, MapPin, Check, X } from 'lucide-react'

const properties = [
  { name: 'Modern Apartment', place: 'Ulpiana · Prishtina', price: '€165,000', beds: 2, baths: 2, size: '98 m²', image: '/forma/hero.png' },
  { name: 'Penthouse Residence', place: 'Veternik · Prishtina', price: '€320,000', beds: 3, baths: 3, size: '182 m²', image: '/forma/hero.png' },
  { name: 'Family House', place: 'Ferizaj', price: '€245,000', beds: 4, baths: 3, size: '260 m²', image: '/forma/hero.png' },
]

export function FormaPropertiesApp() {
  const [mode, setMode] = useState<'Buy' | 'Rent'>('Buy')
  const [selected, setSelected] = useState<(typeof properties)[number] | null>(null)
  const [saved, setSaved] = useState<string[]>([])
  const [viewing, setViewing] = useState(false)
  const [sell, setSell] = useState(false)
  return <div className="theme-forma min-h-screen bg-[#f7f6f3] text-[#20201d] font-sans">
    <header className="sticky top-11 z-30 border-b border-[#20201d]/10 bg-[#f7f6f3]/90 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="/forma-properties" className="font-serif text-xl tracking-tight">forma <span className="font-sans text-xs uppercase tracking-widest text-[#20201d]/40">properties</span></a><nav className="hidden gap-7 text-sm text-[#20201d]/60 md:flex"><a href="#properties">Properties</a><a href="#properties">Buy</a><a href="#properties">Rent</a><button onClick={() => setSell(true)}>Sell</button><a href="#about">About</a></nav><button onClick={() => setSell(true)} className="rounded-full bg-[#20201d] px-5 py-2.5 text-sm text-white">Request valuation</button></div></header>
    <main>
      <section className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:py-24"><div className="self-center"><p className="text-xs uppercase tracking-[.25em] text-[#8b6a4b]">Forma Properties · Prishtina</p><h1 className="mt-5 max-w-xl font-serif text-5xl leading-[1.04] tracking-tight sm:text-7xl">Find a place that feels like yours.</h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-[#20201d]/60">Premium residential and commercial properties selected for how you want to live, work, and grow.</p><div className="mt-10 border border-[#20201d]/15 bg-white p-3 shadow-sm"><div className="flex gap-1 border-b border-[#20201d]/10 pb-3">{(['Buy','Rent'] as const).map(t => <button key={t} onClick={() => setMode(t)} className={`px-4 py-2 text-sm ${mode === t ? 'bg-[#20201d] text-white' : 'text-[#20201d]/50'}`}>{t}</button>)}</div><div className="grid gap-3 pt-3 sm:grid-cols-3"><select className="h-11 border border-[#20201d]/15 bg-transparent px-3 text-sm"><option>Prishtina</option><option>Ferizaj</option><option>Peja</option></select><select className="h-11 border border-[#20201d]/15 bg-transparent px-3 text-sm"><option>Any property</option><option>Apartment</option><option>House</option></select><button onClick={() => document.getElementById('properties')?.scrollIntoView({ behavior: 'smooth' })} className="h-11 bg-[#8b6a4b] px-4 text-sm text-white">Search properties</button></div></div></div><div className="relative min-h-[480px] overflow-hidden"><Image src="/forma/hero.png" alt="Modern architecture in Kosovo" fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 55vw"/><div className="absolute bottom-5 left-5 bg-white/90 px-5 py-4 backdrop-blur"><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">Featured address</p><p className="mt-1 font-serif text-xl">The Veternik Collection</p></div></div></section>
      <section id="properties" className="border-y border-[#20201d]/10 bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.25em] text-[#8b6a4b]">Curated listings</p><h2 className="mt-4 font-serif text-4xl tracking-tight">Properties worth coming home to.</h2></div><div className="flex items-center gap-2 text-sm text-[#20201d]/55"><button className="border border-[#20201d]/15 bg-[#f7f6f3] px-4 py-2 text-[#20201d]">Grid view</button><button className="px-4 py-2">Map view</button></div></div><div className="mt-12 grid gap-8 md:grid-cols-3">{properties.map(p => <article key={p.name} className="group"><button onClick={() => setSelected(p)} className="relative block aspect-[4/3] w-full overflow-hidden text-left"><Image src={p.image} alt={p.name} fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw"/><span className="absolute left-3 top-3 bg-white px-3 py-1 text-[10px] uppercase tracking-widest">For {mode.toLowerCase()}</span><button onClick={e => { e.stopPropagation(); setSaved(s => s.includes(p.name) ? s.filter(x => x !== p.name) : [...s, p.name]) }} className="absolute right-3 top-3 flex size-9 items-center justify-center bg-white"><Heart className={`size-4 ${saved.includes(p.name) ? 'fill-[#8b6a4b] text-[#8b6a4b]' : ''}`} /></button></button><button onClick={() => setSelected(p)} className="mt-4 block text-left"><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">{p.place}</p><h3 className="mt-2 font-serif text-2xl">{p.name}</h3><p className="mt-2 text-lg">{p.price}</p><div className="mt-3 flex gap-4 text-xs text-[#20201d]/55"><span className="flex items-center gap-1"><BedDouble className="size-3.5"/>{p.beds} bedrooms</span><span className="flex items-center gap-1"><Bath className="size-3.5"/>{p.baths} bathrooms</span><span className="flex items-center gap-1"><Maximize className="size-3.5"/>{p.size}</span></div></button></article>)}</div></div></section>
      <section id="about" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-8 border-t border-[#20201d]/10 pt-10 md:grid-cols-3"><div><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">01 / Local perspective</p><p className="mt-4 text-sm leading-relaxed text-[#20201d]/60">We know the streets, developers, and details that make a property a good decision.</p></div><div><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">02 / Clear guidance</p><p className="mt-4 text-sm leading-relaxed text-[#20201d]/60">From first viewing to signed keys, our advice stays direct and personal.</p></div><div><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">03 / Better listings</p><p className="mt-4 text-sm leading-relaxed text-[#20201d]/60">Thoughtful photography, accurate facts, and homes presented with respect.</p></div></div></section>
    </main>
    {selected && <PropertyModal property={selected} onClose={() => setSelected(null)} onViewing={() => { setSelected(null); setViewing(true) }} />}
    {viewing && <ViewingModal onClose={() => setViewing(false)} />}
    {sell && <SellModal onClose={() => setSell(false)} />}
  </div>
}

function PropertyModal({ property, onClose, onViewing }: { property: (typeof properties)[number]; onClose: () => void; onViewing: () => void }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#20201d]/40 sm:items-center sm:p-5"><div className="relative max-h-[90vh] w-full max-w-3xl overflow-auto bg-white p-6 sm:p-8"><button onClick={onClose} className="absolute right-5 top-5"><X className="size-5"/></button><div className="grid gap-8 sm:grid-cols-2"><div className="relative aspect-square overflow-hidden"><Image src={property.image} alt={property.name} fill className="object-cover"/></div><div><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">{property.place}</p><h2 className="mt-3 font-serif text-4xl">{property.name}</h2><p className="mt-3 text-2xl">{property.price}</p><p className="mt-6 text-sm leading-relaxed text-[#20201d]/60">A considered residence with generous proportions, warm materials, and the everyday details that make a home feel effortless.</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><span>{property.size}</span><span>{property.beds} bedrooms</span><span>{property.baths} bathrooms</span><span>2 parking spaces</span></div><div className="mt-8 flex gap-3"><button onClick={onViewing} className="flex-1 bg-[#20201d] px-4 py-3 text-sm text-white">Request a viewing</button><button className="border border-[#20201d]/15 px-4 py-3 text-sm">Contact agent</button></div></div></div></div></div> }

function ViewingModal({ onClose }: { onClose: () => void }) { const [done, setDone] = useState(false); const [date, setDate] = useState(''); const [time, setTime] = useState(''); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const valid = date && time && name.length > 1 && phone.length > 5; return <ModalShell onClose={onClose}>{done ? <Success title="Viewing request sent" copy="A Forma advisor will contact you to confirm the appointment." onClose={onClose}/> : <><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">Private viewing</p><h2 className="mt-2 font-serif text-3xl">Choose a time to visit.</h2><div className="mt-6 space-y-3"><input type="date" value={date} onChange={e => setDate(e.target.value)} className="h-12 w-full border border-[#20201d]/15 px-3"/><div className="grid grid-cols-3 gap-2">{['10:00','12:30','15:00'].map(t => <button key={t} onClick={() => setTime(t)} className={`h-11 border text-sm ${time === t ? 'bg-[#20201d] text-white' : ''}`}>{t}</button>)}</div><input placeholder="Name" value={name} onChange={e => setName(e.target.value)} className="h-12 w-full border border-[#20201d]/15 px-3"/><input placeholder="Phone" value={phone} onChange={e => setPhone(e.target.value)} className="h-12 w-full border border-[#20201d]/15 px-3"/></div><button disabled={!valid} onClick={() => setDone(true)} className="mt-6 w-full bg-[#20201d] py-3 text-sm text-white disabled:opacity-40">Request viewing</button></>}</ModalShell> }
function SellModal({ onClose }: { onClose: () => void }) { const [done, setDone] = useState(false); return <ModalShell onClose={onClose}>{done ? <Success title="Valuation request sent" copy="Our property team will review your details and call you shortly." onClose={onClose}/> : <><p className="text-xs uppercase tracking-widest text-[#8b6a4b]">Sell with Forma</p><h2 className="mt-2 font-serif text-3xl">What is your property worth?</h2><div className="mt-6 grid gap-3"><select className="h-12 border border-[#20201d]/15 px-3"><option>Apartment</option><option>House</option><option>Commercial</option></select><input placeholder="Location" className="h-12 border border-[#20201d]/15 px-3"/><input placeholder="Approximate size (m²)" className="h-12 border border-[#20201d]/15 px-3"/><input placeholder="Your name and phone" className="h-12 border border-[#20201d]/15 px-3"/></div><button onClick={() => setDone(true)} className="mt-6 w-full bg-[#20201d] py-3 text-sm text-white">Request valuation</button></>}</ModalShell> }
function ModalShell({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#20201d]/40 sm:items-center sm:p-5"><div className="relative w-full max-w-lg bg-white p-6 sm:p-8"><button onClick={onClose} className="absolute right-5 top-5"><X className="size-5"/></button>{children}</div></div> }
function Success({ title, copy, onClose }: { title: string; copy: string; onClose: () => void }) { return <div className="py-8 text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-full bg-[#ede5da]"><Check className="size-6 text-[#8b6a4b]"/></div><h2 className="mt-5 font-serif text-3xl">{title}</h2><p className="mt-3 text-sm text-[#20201d]/60">{copy}</p><button onClick={onClose} className="mt-7 bg-[#20201d] px-5 py-3 text-sm text-white">Done</button></div> }

export default FormaPropertiesApp
